/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tagplagin;

import org.gradle.api.Plugin;
import org.gradle.api.Project;


public class GitTagPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("tagVersion", TagVersionTask.class);
    }
}
